default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning
  username: rails
  password:

development:
  <<: *default
  database: satilife_development

test:
  <<: *default
  database: satilife_test
